spring.application.name=bamul-customer-master
server.port=9092

# ======================
# ORACLE DATASOURCE - Local Oracle Free 23ai
# ======================
spring.datasource.url=jdbc:oracle:thin:@//129.159.231.57:1521/FREEPDB1
spring.datasource.username=bamul
spring.datasource.password=Bamul2026
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.hikari.maximum-pool-size=10

# ======================
# EMAIL (Gmail SMTP)
# ======================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=guhashibashish@gmail.com
spring.mail.password=suonkwrzquqwijkg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
notification.admin.email=guhashibashish@gmail.com

# ======================
# JPA / HIBERNATE
# ======================
spring.jpa.database-platform=org.hibernate.dialect.Oracle10gDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.proc.param_null_passing=true

# ======================
# LOGGING
# ======================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

server.tomcat.relaxed-query-chars=|,{,},[,]
spring.mvc.dispatch-options-request=true

# ======================
# FILE UPLOAD SIZE
# ======================
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

